### ISSUE TITLE
fails when ansible_connection == netconf

### ISSUE THREAD

**Issue by LukeDRussell** [ansible-network/juniper_junos#14]
When a device has ansible_connection set to netconf:
```sh
TASK [ansible-network.juniper_junos : testing] **********************************************************************************
ok: [tovllpst_sc1] =>
  msg:
  - 'ansible_connection: netconf'
  - 'ansible_network_os: junos'

TASK [ansible-network.juniper_junos : validate ansible_connection == 'network_cli' or ansible_connection == 'netconf'] **********
fatal: [tovllpst_sc1]: FAILED! => changed=false
  msg: expected ansible_network to be `network_cli` or `netconf`, got `netconf`
        to retry, use: --limit @/home/4032956/network-automation/retry/get-facts.retry
```

Expected result:
```sh
TASK [ansible-network.juniper_junos : testing] **********************************************************************************
ok: [tovllpst_sc1] =>
  msg:
  - 'ansible_connection: netconf'
  - 'ansible_network_os: junos'

TASK [ansible-network.juniper_junos : set ansible_provider_functions fact] ******************************************************
ok: [tovllpst_sc1]
```

My fix: 

Edit includes/init.yaml
```yaml
- name: validate ansible_connection == 'network_cli' or ansible_connection == 'netconf'
  fail:
    msg: "expected ansible_network to be `network_cli` or `netconf`, got `{{ ansible_connection }}`"
  when: "not ansible_connection == 'network_cli' and not ansible_connection == 'netconf'"
#  when: "not ansible_connection == 'network_cli' or ansible_connection == 'netconf'"
```
